CREATE TABLE CUSTOMER(
  CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(32),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24),
  ACTIVE_INDICATOR VARCHAR(1)
);

CREATE TABLE BARBER(
  BARBER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  CHAIR_ID BIGINT,
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(32),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24),
  ACTIVE_INDICATOR VARCHAR(1)
);

CREATE TABLE APPOINTMENT(
  APPOINTMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BARBER_ID BIGINT NOT NULL,
  CUSTOMER_ID BIGINT NOT NULL,
  APP_DATE DATETIME,
  ACTIVE_INDICATOR VARCHAR(1)
);

ALTER TABLE APPOINTMENT ADD FOREIGN KEY (BARBER_ID) REFERENCES BARBER(BARBER_ID);
ALTER TABLE APPOINTMENT ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
CREATE INDEX IDX_RES_DATE_ ON APPOINTMENT(APP_DATE);
